/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.edu.sju.ee.eea.ui.workspace.data;

import tw.edu.sju.ee.eea.core.frequency.response.FrequencyResponseFile;
import tw.edu.sju.ee.eea.core.math.ComplexArray;
import tw.edu.sju.ee.eea.core.math.MetricPrefixFormat;
import tw.edu.sju.ee.eea.ui.WorkspacePanel;
import tw.edu.sju.ee.eea.ui.swing.pane.FrequencyResponseConfigPane;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import org.apache.commons.math3.complex.Complex;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.LogAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYItemRenderer;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Leo
 */
public class FrequencyResponsePanel extends WorkspacePanel<FrequencyResponseFile> {

//    private FrequencyResponseFile file;
    private JFreeChart chart;
    private ChartPanel chartPanel;

    public FrequencyResponsePanel(File file, FrequencyResponseFile data) {
        super(file);
        this.data = data;

        initChart();
        initComponents();
    }

    /**
     * Creates new form FrequencyResponsePanel
     */
    public FrequencyResponsePanel(FrequencyResponseFile data) {
        this(new File("new Frequency Response"), data);
    }

    private void initChart() {
        Complex[] H = new Complex[data.getConfig().getLength()];
        for (int i = 0; i < H.length; i++) {
            H[i] = data.getOut()[i].divide(data.getIn()[i]);
        }

        Font font = new Font(Font.DIALOG, Font.BOLD, 14);
        Color color1 = Color.RED;
        Color color2 = Color.BLUE;

        chart = ChartFactory.createXYLineChart("Bode Plot", null, "Magnitude(dB)", createXYSeriesCollection("Magnitude", data, toBode(ComplexArray.getAbsolute(H))), PlotOrientation.VERTICAL, true, true, false);
        XYPlot plot = chart.getXYPlot();

        LogAxis domainAxis = new LogAxis("Frequency");
        domainAxis.setLabelFont(font);
        domainAxis.setNumberFormatOverride(new MetricPrefixFormat("0.###"));
        plot.setDomainAxis(domainAxis);

        ValueAxis axis1 = plot.getRangeAxis();
        axis1.setLabelFont(font);
        axis1.setLabelPaint(color1);
        axis1.setTickLabelPaint(color1);

        NumberAxis axis2 = new NumberAxis("Phase(Degrees)");
        axis2.setLabelFont(font);
        axis2.setLabelPaint(color2);
        axis2.setTickLabelPaint(color2);
        plot.setRangeAxis(1, axis2);

        plot.setDataset(1, createXYSeriesCollection("Phase", data, toDegree(ComplexArray.getArgument(H))));
        plot.mapDatasetToRangeAxis(1, 1);
        XYItemRenderer renderer2 = new StandardXYItemRenderer();
        renderer2.setSeriesPaint(0, color2);
        plot.setRenderer(1, renderer2);

        chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(600, 270));
        chartPanel.setDomainZoomable(true);
        chartPanel.setRangeZoomable(true);
    }

    private static XYSeriesCollection createXYSeriesCollection(String name, FrequencyResponseFile file, double[] data) {
        XYSeries series1 = new XYSeries(name);
        for (int i = 0; i < file.getConfig().getLength(); i++) {
            series1.add(file.getConfig().getFrequency(i), data[i]);
        }
        XYSeriesCollection collection = new XYSeriesCollection();
        collection.addSeries(series1);
        return collection;
    }

    private double[] toBode(double[] data) {
        double bode[] = new double[data.length];
        for (int i = 0; i < data.length; i++) {
            bode[i] = 20 * Math.log(data[i]);
        }
        return bode;
    }

    private double[] toDegree(double[] data) {
        double degree[] = new double[data.length];
        for (int i = 0; i < data.length; i++) {
            degree[i] = Math.toDegrees(data[i]);
        }
        return degree;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frequencyResponseConfigPane1 = new FrequencyResponseConfigPane(this.data.getConfig());
        jPanel1 = chartPanel;

        setPreferredSize(new java.awt.Dimension(1280, 720));

        frequencyResponseConfigPane1.setMinimumSize(new java.awt.Dimension(300, 200));
        frequencyResponseConfigPane1.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(frequencyResponseConfigPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(frequencyResponseConfigPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tw.edu.sju.ee.eea.ui.swing.pane.FrequencyResponseConfigPane frequencyResponseConfigPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
