/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tw.edu.sju.ee.eea.ui.screen;

import javax.swing.JPanel;

/**
 *
 * @author Leo
 */
public class GridPanel extends JPanel {

    private GridConfigure conf;
    
    /**
     * Creates new form NewBeanForm
     */
    public GridPanel() {
        initComponents();
    }

    public void setConf(GridConfigure conf) {
        this.conf = conf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
