/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sju.ee98.daq.ui.workspace.data;

import edu.sju.ee.daq.core.math.ComplexArray;
import edu.sju.ee98.daq.core.frequency.response.FrequencyResponseFile;
import edu.sju.ee98.daq.ui.WorkPanel;
import java.awt.Color;
import org.apache.commons.math3.complex.Complex;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.LogarithmicAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYItemRenderer;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Leo
 */
public class FrequencyResponsePanel extends WorkPanel {

    private FrequencyResponseFile file;
    private JFreeChart chart;

    /**
     * Creates new form FrequencyResponsePanel
     */
    public FrequencyResponsePanel(FrequencyResponseFile file) {
        this.file = file;
        initChart();
        initComponents();
    }

    private void initChart() {
        Complex[] H = new Complex[file.getConfig().getLength()];
        for (int i = 0; i < H.length; i++) {
            H[i] = file.getOut()[i].divide(file.getIn()[i]);
        }

        Color color1 = Color.RED;
        Color color2 = Color.GREEN;
        
        chart = ChartFactory.createXYLineChart("title", "Frequency", "H", createXYSeriesCollection(file, ComplexArray.getAbsolute(H)));
        XYPlot plot = chart.getXYPlot();
        plot.setDomainAxis(new LogarithmicAxis("df"));
        
        
        NumberAxis axis2 = new NumberAxis("Range Axis 2");
        axis2.setLabelPaint(color2);
        axis2.setTickLabelPaint(color2);
        plot.setRangeAxis(1, axis2);

        plot.setDataset(1, createXYSeriesCollection(file, ComplexArray.getArgument(H)));
        plot.mapDatasetToRangeAxis(1, 1);
        XYItemRenderer renderer2 = new StandardXYItemRenderer();
        renderer2.setSeriesPaint(0, color2);
        plot.setRenderer(1, renderer2);
    }
    
    private static XYSeriesCollection createXYSeriesCollection(FrequencyResponseFile file, double[] data) {
        XYSeries series1 = new XYSeries("Average Weight");
        for (int i = 0; i < file.getConfig().getLength(); i++) {
            series1.add(file.getConfig().getFrequency(i), data[i]);
        }
        XYSeriesCollection collection = new XYSeriesCollection();
        collection.addSeries(series1);
        return collection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frequencyResponseConfigPane1 = new edu.sju.ee98.daq.ui.swing.pane.FrequencyResponseConfigPane();
        jPanel1 = new ChartPanel(chart);

        setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(frequencyResponseConfigPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(frequencyResponseConfigPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 332, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.sju.ee98.daq.ui.swing.pane.FrequencyResponseConfigPane frequencyResponseConfigPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
